services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dmojroot
      MYSQL_DATABASE: dmoj
      MYSQL_USER: dmoj
      MYSQL_PASSWORD: dmojpass
    volumes:
      - db_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  site:
    build:
      context: .
      dockerfile: ./docker/site/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./problems:/problems
      - site_static:/app/static
      - site_media:/app/media
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=dmoj
      - MYSQL_USER=dmoj
      - MYSQL_PASSWORD=dmojpass
      - REDIS_HOST=redis
      - VIRTUAL_HOST=icodedn.com
      - VIRTUAL_PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bridged:
    build:
      context: .
      dockerfile: ./docker/site/Dockerfile
    restart: always
    depends_on:
      site:
        condition: service_healthy
    command: python manage.py runbridged
    volumes:
      - ./problems:/problems
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=dmoj
      - MYSQL_USER=dmoj
      - MYSQL_PASSWORD=dmojpass
      - REDIS_HOST=redis
    ports:
      - "9999:9999"

  celery:
    build:
      context: .
      dockerfile: ./docker/site/Dockerfile
    restart: always
    depends_on:
      site:
        condition: service_healthy
    command: celery -A dmoj_celery worker
    volumes:
      - ./problems:/problems
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=dmoj
      - MYSQL_USER=dmoj
      - MYSQL_PASSWORD=dmojpass
      - REDIS_HOST=redis

  wsevent:
    build:
      context: .
      dockerfile: ./docker/site/Dockerfile
    restart: always
    depends_on:
      site:
        condition: service_healthy
    command: node websocket/daemon.js
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=dmoj
      - MYSQL_USER=dmoj
      - MYSQL_PASSWORD=dmojpass
      - REDIS_HOST=redis
    ports:
      - "15100:15100"
      - "15101:15101"
      - "15102:15102"

  judge:
    build:
      context: .
      dockerfile: ./docker/judge/Dockerfile
      args:
        - CACHEBUST=1
    image: dmoj-judge:latest
    restart: always
    depends_on:
      bridged:
        condition: service_started
    volumes:
      - ./problems:/problems
    environment:
      - JUDGE_NAME=judge1
      - JUDGE_KEY=verysecretkey
      - BRIDGE_ADDRESS=bridged
      - BRIDGE_PORT=9999
    cap_add:
      - SYS_PTRACE

volumes:
  db_data:
  redis_data:
  site_static:
  site_media: 