services:
  site:
    environment:
      - DEBUG=True
    volumes:
      - ./dmoj-site:/app
    ports:
      - "8000:8000"
      - "9998:9998"
      - "9999:9999"
      - "15100:15100"
      - "15101:15101"
      - "15102:15102"

  bridged:
    volumes:
      - ./dmoj-site:/app

  celery:
    volumes:
      - ./dmoj-site:/app

  wsevent:
    volumes:
      - ./dmoj-site:/app
    ports:
      - "15100:15100"
      - "15101:15101"
      - "15102:15102"

  judge:
    build:
      args:
        CACHEBUST: "${RANDOM:-1}" 