services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dmojroot
      MYSQL_DATABASE: dmoj
      MYSQL_USER: dmoj
      MYSQL_PASSWORD: dmojpass
    volumes:
      - db_data:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  site:
    build:
      context: .
      dockerfile: ./docker/site/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=dmoj
      - MYSQL_USER=dmoj
      - MYSQL_PASSWORD=dmojpass
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - DMOJ_IN_DOCKER=1
    volumes:
      - ./dmoj-site:/app
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"

  judge:
    build:
      context: .
      dockerfile: ./docker/judge/Dockerfile
    restart: always
    depends_on:
      - site
    environment:
      - JUDGE_NAME=judge1
      - JUDGE_KEY=verysecretkey
      - BRIDGE_ADDRESS=site
      - BRIDGE_PORT=9999
    volumes:
      - ./problems:/problems
    networks:
      - default

volumes:
  db_data:
  redis_data:
  static:
  media: 